language: python
python:
  - "2.7"
before_install:
  - pip install pytest-cov
  - pip install coveralls
script:
  - py.test tests/ --cov coveralls --cov-report term-missing
after_success:
  - coveralls
